spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/global_order_management?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect